name: Build-FF-iOS
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential perl git curl libssl-dev xz-utils libtinfo5 libncurses5
          
      - name: Install Theos (Manual)
        run: |
          git clone --recursive --depth 1 https://github.com/theos/theos.git ~/theos
          
      - name: Install iOS SDK (Manual)
        run: |
          mkdir -p ~/theos/sdks
          git clone --depth 1 https://github.com/theos/sdks.git ~/theos/sdks
          
      - name: Install Toolchain (Sbingner)
        run: |
          mkdir -p ~/theos/toolchain/linux/iphone
          curl -L "https://github.com/sbingner/llvm-project/releases/download/v10.0.0-1/linux-ios-arm64e-clang-toolchain.tar.lzma" -o toolchain.tar.lzma
          tar -xf toolchain.tar.lzma --strip-components=1 -C ~/theos/toolchain/linux/iphone
          rm toolchain.tar.lzma
          
      - name: Compile Tweak
        run: |
          export THEOS=~/theos
          export PATH=$THEOS/toolchain/linux/iphone/bin:$PATH
          # Lệnh nấu chính
          make package
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hack-FF-Thành-Phẩm
          path: packages/*.deb
