name: Build-FF-iOS
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential perl git curl libssl-dev
          export THEOS=~/theos
          # Tải Theos rút gọn
          git clone --recursive --depth 1 https://github.com/theos/theos.git $THEOS
          
      - name: Setup iOS SDK (Fix Directory Exists)
        run: |
          export THEOS=~/theos
          # Xóa thư mục cũ để tránh lỗi "already exists"
          rm -rf $THEOS/sdks
          # Tải SDK bản siêu nhanh
          git clone --depth 1 https://github.com/theos/sdks.git $THEOS/sdks
          
      - name: Compile Tweak
        run: |
          export THEOS=~/theos
          # Lệnh nấu chính thức
          make package
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hack-FF-Thanh-Pham
          path: packages/*.deb
